services:
  - type: web
    name: remigianum-monopoly-server
    runtime: node
    region: frankfurt
    plan: free
    rootDir: server
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_ORIGIN
        sync: false

  - type: static
    name: remigianum-monopoly-client
    region: frankfurt
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_SOCKET_URL
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
